### ISSUE TITLE
Readme de referência :p

### ISSUE THREAD

**Issue by cuchas** [rodolfofadino/fp_18_2_web_aula_4#1]
Oi Professor,

Seria muito bom se em cada aula houvesse um resuminho no readme, ou link pro material de referencia para ajudar nos estudos do final de semana! :)

**Comment by rodolfofadino** [comment]
Aproveite a chance de receber todo o material completo e ainda contato com nossos professores => https://www.fiap.com.br https://www.fiap.com.br/mba/mba-em-arquitetura-e-desenvolvimento-na-plataforma-net/

**Comment by cleberdantas** [comment]
LGTM

**Comment by cuchas** [comment]
#grosso :p
